name = "zg6502"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
licenses = "MIT"
website = ""
tags = []

[build-switches]
"*".style_checks = "No"
